# Version del docker-compose a utilizar
version: "3.7"
services:
  # docker run --name some-mysql -v /my/own/datadir:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:tag
  mysql:
    image: mysql:5.6.45
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    deploy:
      replicas: 1
    environment:
      - MYSQL_ROOT_PASSWORD=mysql*passwd
    ports: 
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql


